### ISSUE TITLE
JavaDoc Location

### ISSUE THREAD

**Issue by DonyorM** [wireapp/bot-sdk#7]
Thanks for putting this together, this is a really nice SDK.

However, I'd love to be able to build a javadoc jar for the SDK. I tried building one myself, but it didn't seem to work. Do you have a javadoc jar I could add to my IDE? Or Maven be made to handle building it itself?

**Comment by dkovacevic** [comment]
Merged. Please let us know if this solution works for you. Thanks for reporting!
